# Generated by Django 4.2.25 on 2025-10-23 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(max_length=100)),
                ('web', models.CharField(blank=True, default='', max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_lector', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_lector', models.CharField(max_length=255)),
                ('correo_lector', models.CharField(blank=True, default='', max_length=255)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fisico', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='codigo',
            new_name='codigo_comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='nombre_comuna',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='bio',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria'),
        ),
        migrations.AddField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipocategoria'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion'),
        ),
    ]
